version: '3'
services:
  app:
    build: .
    ports:
      - "8004:8004"
    volumes:
      - ./app.db:/app/app.db
    environment:
      - FLASK_APP = app.py
      - FLASK_ENV = development
